### ISSUE TITLE
您好，我在运行建图launch的时候出现了下图的问题，请问是什么原因呢？

### ISSUE THREAD

**Issue by liujiacheng1009** [mushroom-x/aruco_mapping2#1]
![image](https://user-images.githubusercontent.com/26436149/55286564-da75ce00-53cf-11e9-80a5-c6fea88e6bb9.png)

我还有一点疑问，那个PyKDL包需要单独安装吗？是不是在完整版内已经包含了呢？

**Comment by luwc1009** [comment]
要将python文件
